@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZjY3NTRmZC04YzdlLTQ4ZDUtYWU0MC1mZWQxOTUyZmY1YjEiLCJlbWFpbCI6Imhha2lteWFraW0yMDBAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUwOTM4Nzc4LCJleHAiOjE3NTEwMjUxNzh9.UuSUdub7QkvPoSjejzG0Iy8VhGZyKRxHHK1QKH13Daw
@AGENT_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MjMwM2Y4Ni02MDJkLTQ1NjMtYWJlOC05ZjBjYzJiODVkYWIiLCJlbWFpbCI6Imhha2dvdGNoaWxsc0BnbWFpbC5jb20iLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NTA5Mzg4MTgsImV4cCI6MTc1MTAyNTIxOH0.g1J9ygGKq0yWFIFsH8hHp27LDklUjVZ5A3da8_7PumY
@CUSTOMER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNTEyN2Q4Ny03ZWIzLTRlOWYtYjg4NC03NjljMWIxMmE3ZWEiLCJlbWFpbCI6Imp1c3RoYWtpbW1AZ21haWwuY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzUwOTM4ODM2LCJleHAiOjE3NTEwMjUyMzZ9.o6HzKAbP95DtbXMLEQgVuhWFFt77O_Bp4-5iC8HGrMc
### 👤 Get Logged-in User Profile (as Admin)
GET http://localhost:3000/user/me
Authorization: Bearer {{ADMIN_TOKEN}}

### 👤 Get Logged-in User Profile (as Agent)
GET http://localhost:3000/user/me
Authorization: Bearer {{AGENT_TOKEN}}

### 👤 Get Logged-in User Profile (as Customer)
GET http://localhost:3000/user/me
Authorization: Bearer {{CUSTOMER_TOKEN}}
