@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNTEyN2Q4Ny03ZWIzLTRlOWYtYjg4NC03NjljMWIxMmE3ZWEiLCJlbWFpbCI6Imp1c3RoYWtpbW1AZ21haWwuY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzUwOTQwNTA1LCJleHAiOjE3NTEwMjY5MDV9.K0SfyRwCOO9pitwD3oTWBIB1NojdHTwOWUQmtWOfjyI

### 🔐 Change Password
PATCH http://localhost:3000/user/change-password
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "currentPassword": "hakim20",
  "newPassword": "hakim200"
}
