@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZGU1Yzc0Ni05MGJmLTQ3MDUtYTI3Yi1iOWI3MDE2OTE3ZDUiLCJlbWFpbCI6Imhha2lteWFraW0yMDBAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUxNDQ2MjU1LCJleHAiOjE3NTE1MzI2NTV9.NmLhBHNiW0Sun5oCXCDH6J7h5hoXg2QkZUJivqPhM4M
@AGENT_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MjMwM2Y4Ni02MDJkLTQ1NjMtYWJlOC05ZjBjYzJiODVkYWIiLCJlbWFpbCI6Imhha2dvdGNoaWxsc0BnbWFpbC5jb20iLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NTEwMjYyNzUsImV4cCI6MTc1MTExMjY3NX0.63HFchM2Lq-1NDIQWsai5u_FkSFkgzPCpbYQHpw5sZ0
@CUSTOMER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZGU1Yzc0Ni05MGJmLTQ3MDUtYTI3Yi1iOWI3MDE2OTE3ZDUiLCJlbWFpbCI6Imhha2lteWFraW0yMDBAZ21haWwuY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzUxMjcxNDkxLCJleHAiOjE3NTEzNTc4OTF9.37ImrBXEbosjg_xD7SxdjFNlfG1YCBKLuel-N6ya7f8
### ✅ Create Booking
POST http://localhost:3000/booking
Authorization: Bearer {{CUSTOMER_TOKEN}}
Content-Type: application/json

{
  "vehicleId": "050e82f1-aa07-4d0e-b8ea-76d9bafaad77",
  "startDate": "2025-7-11",
  "endDate": "2025-07-12",
  "location": "Nairobi"
}

### 📄 Get My Bookings
GET http://localhost:3000/booking/me
Authorization: Bearer {{CUSTOMER_TOKEN}}

### 🔁 Approve Booking
PATCH http://localhost:3000/booking/db77e68f-afca-4d1f-a456-78efacb9ca83/status
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
  "status": "CONFIRMED"
}

### Update Booking Status to Completed
PATCH http://localhost:3000/booking/db77e68f-afca-4d1f-a456-78efacb9ca83/status
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "status": "COMPLETED"
}


### ❌ Reject Booking
PATCH http://localhost:3000/booking/816c5914-b2da-4c72-84e5-d490a21a7398/status
Authorization: Bearer {{AGENT_TOKEN}}
Content-Type: application/json

{
  "status": "REJECTED"
}

### ❌ Cancel Booking (Customer)
DELETE http://localhost:3000/booking/4474403e-b3b7-42ab-bec1-050815dae310
Authorization: Bearer {{CUSTOMER_TOKEN}}


### 🧾 Get Invoice (HTML)
GET http://localhost:3000/booking/a70cac1c-07d3-4355-8094-642ed02430d7/invoice
Authorization: Bearer {{CUSTOMER_TOKEN}}


### 🔍 All bookings
GET http://localhost:3000/booking
Authorization: Bearer {{ADMIN_TOKEN}}

### 🔍 Bookings by status
GET http://localhost:3000/booking?status=COMPLETED
Authorization: Bearer {{AGENT_TOKEN}}

### 🔍 Bookings in July
GET http://localhost:3000/booking?startDate=2025-07-01&endDate=2025-07-31
Authorization: Bearer {{ADMIN_TOKEN}}
