@ADMIN_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZGU1Yzc0Ni05MGJmLTQ3MDUtYTI3Yi1iOWI3MDE2OTE3ZDUiLCJlbWFpbCI6Imhha2lteWFraW0yMDBAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUxNDQ2MjU1LCJleHAiOjE3NTE1MzI2NTV9.NmLhBHNiW0Sun5oCXCDH6J7h5hoXg2QkZUJivqPhM4M
@AGENT_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4MjMwM2Y4Ni02MDJkLTQ1NjMtYWJlOC05ZjBjYzJiODVkYWIiLCJlbWFpbCI6Imhha2dvdGNoaWxsc0BnbWFpbC5jb20iLCJyb2xlIjoiQUdFTlQiLCJpYXQiOjE3NTEwMjYyNzUsImV4cCI6MTc1MTExMjY3NX0.63HFchM2Lq-1NDIQWsai5u_FkSFkgzPCpbYQHpw5sZ0
@CUSTOMER_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWI3YjVhZC0yMDNhLTRkMjItOWJkOC0wNmEzMTk3NzQ0YzMiLCJlbWFpbCI6Imp1c3RoYWtpbW1AZ21haWwuY29tIiwicm9sZSI6IkNVU1RPTUVSIiwiaWF0IjoxNzUxNDQ2MjM2LCJleHAiOjE3NTE1MzI2MzZ9.h7JPIlYtY20TQZidIBViekvVdtAqmDyLjRdoWa6xiCY
### 👤 Get Logged-in User Profile (as Admin)
GET http://localhost:3000/user/me
Authorization: Bearer {{ADMIN_TOKEN}}

### 👤 Get Logged-in User Profile (as Agent)
GET http://localhost:3000/user/me
Authorization: Bearer {{AGENT_TOKEN}}

### 👤 Get Logged-in User Profile (as Customer)
GET http://localhost:3000/user/me
Authorization: Bearer {{CUSTOMER_TOKEN}}


### Request token
POST http://localhost:3000/auth/forgot-password
Content-Type: application/json

{
  "email": "hakimyakim200@gmail.com"
}


### Reset Password with Token
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "13ca7a8f9e5ff1f6c86940ac15233d54a2af04843d7920da4f4688eb6e790757",
  "newPassword": "hakim200",
  "confirmPassword": "hakim200"
}


### 📊 Get System Stats (Admin only)
GET http://localhost:3000/user/stats
Authorization: Bearer {{ADMIN_TOKEN}}


### 👥 All users
GET http://localhost:3000/user/all
Authorization: Bearer {{ADMIN_TOKEN}}

### 👥 Filter by role
GET http://localhost:3000/user/all?role=AGENT
Authorization: Bearer {{ADMIN_TOKEN}}

### 👥 Filter by date range
GET http://localhost:3000/user/all?startDate=2025-06-01&endDate=2025-06-30
Authorization: Bearer {{ADMIN_TOKEN}}

### 🔍 Search by name/email
GET http://localhost:3000/user/all?search=abdul
Authorization: Bearer {{ADMIN_TOKEN}}


### Create a Review
POST http://localhost:3000/reviews
Content-Type: application/json
Authorization: Bearer {{CUSTOMER_TOKEN}}

{
  "vehicleId": "a70a32c1-1be7-4122-ac32-3ea780abf478",
  "rating": 5,
  "comment": "Amazing ride! Smooth and clean."
}

### Get Reviews for a Vehicle
GET http://localhost:3000/reviews/vehicle/cb9db4ac-182a-4ace-bf24-86ceac5a4e38
